# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import urgence_pb2 as urgence__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in urgence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UrgenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAlert = channel.unary_unary(
                '/urgence.UrgenceService/CreateAlert',
                request_serializer=urgence__pb2.AlertRequest.SerializeToString,
                response_deserializer=urgence__pb2.AlertResponse.FromString,
                _registered_method=True)
        self.GetAlertStatus = channel.unary_unary(
                '/urgence.UrgenceService/GetAlertStatus',
                request_serializer=urgence__pb2.StatusRequest.SerializeToString,
                response_deserializer=urgence__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListenAlerts = channel.unary_stream(
                '/urgence.UrgenceService/ListenAlerts',
                request_serializer=urgence__pb2.StatusRequest.SerializeToString,
                response_deserializer=urgence__pb2.AlertStream.FromString,
                _registered_method=True)


class UrgenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlertStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UrgenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlert,
                    request_deserializer=urgence__pb2.AlertRequest.FromString,
                    response_serializer=urgence__pb2.AlertResponse.SerializeToString,
            ),
            'GetAlertStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlertStatus,
                    request_deserializer=urgence__pb2.StatusRequest.FromString,
                    response_serializer=urgence__pb2.StatusResponse.SerializeToString,
            ),
            'ListenAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenAlerts,
                    request_deserializer=urgence__pb2.StatusRequest.FromString,
                    response_serializer=urgence__pb2.AlertStream.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'urgence.UrgenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('urgence.UrgenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UrgenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/urgence.UrgenceService/CreateAlert',
            urgence__pb2.AlertRequest.SerializeToString,
            urgence__pb2.AlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlertStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/urgence.UrgenceService/GetAlertStatus',
            urgence__pb2.StatusRequest.SerializeToString,
            urgence__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/urgence.UrgenceService/ListenAlerts',
            urgence__pb2.StatusRequest.SerializeToString,
            urgence__pb2.AlertStream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
