# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: urgence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'urgence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rurgence.proto\x12\x07urgence\"h\n\x0c\x41lertRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08severity\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"H\n\rAlertResponse\x12\x0f\n\x07\x61lertId\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\restimatedTime\x18\x03 \x01(\x05\" \n\rStatusRequest\x12\x0f\n\x07\x61lertId\x18\x01 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"<\n\x0b\x41lertStream\x12\x0f\n\x07\x61lertId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\xd1\x01\n\x0eUrgenceService\x12<\n\x0b\x43reateAlert\x12\x15.urgence.AlertRequest\x1a\x16.urgence.AlertResponse\x12\x41\n\x0eGetAlertStatus\x12\x16.urgence.StatusRequest\x1a\x17.urgence.StatusResponse\x12>\n\x0cListenAlerts\x12\x16.urgence.StatusRequest\x1a\x14.urgence.AlertStream0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'urgence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERTREQUEST']._serialized_start=26
  _globals['_ALERTREQUEST']._serialized_end=130
  _globals['_ALERTRESPONSE']._serialized_start=132
  _globals['_ALERTRESPONSE']._serialized_end=204
  _globals['_STATUSREQUEST']._serialized_start=206
  _globals['_STATUSREQUEST']._serialized_end=238
  _globals['_STATUSRESPONSE']._serialized_start=240
  _globals['_STATUSRESPONSE']._serialized_end=272
  _globals['_ALERTSTREAM']._serialized_start=274
  _globals['_ALERTSTREAM']._serialized_end=334
  _globals['_URGENCESERVICE']._serialized_start=337
  _globals['_URGENCESERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
